name: Api

on:
  push:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: OhiruFinderApi
    - name: Test with Gradle
      run: ./gradlew test
      working-directory: OhiruFinderApi

  deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Install CF CLI
      run: sudo wget -qO - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    - run: sudo apt-get update
    - run: sudo apt-get install -y cf-cli
    - name: CF login
      run: cf login -a api.run.pivotal.io -u ${{secrets.CF_USERNAME}} -p ${{secrets.CF_PASSWORD}} -o ${{secrets.CF_ORG}} -s ${{secrets.CF_SPACE}}

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      working-directory: OhiruFinderApi
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: OhiruFinderApi
      run: ./gradlew assemble

    - name: CF Push
      working-directory: OhiruFinderApi
      run: cf push ohiru-finder-api -p ./build/libs/ohirufinder-0.0.1-SNAPSHOT.jar

